-- 테이블 생성하기
CREATE TABLE TBL_MEMBER(
	-- 어떤 데이터를 저장하고 싶은지 명시
	NAME VARCHAR(20),
	AGE NUMBER
);

-- 테이블 삭제
DROP TABLE TBL_MEMBER;

-- 제약조건을 가지는 CAR 테이블 만들기
-- CONSTRAINT 제약조건명 제약조건종류(컬럼명)
CREATE TABLE TBL_CAR(
	ID NUMBER,
	BRAND VARCHAR2(100),
	COLOR VARCHAR2(100),
	PRICE NUMBER,
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);

CREATE TABLE EX1(
	COL1 VARCHAR2(10) PRIMARY KEY,
	COL2 VARCHAR2(10) NOT NULL UNIQUE,
	-- 데이터를 넣지 않을 시 현재 시간이 들어간다.
	CREATE_DATE DATE DEFAULT SYSDATE
);

-- 컬럼명 변경
ALTER TABLE EX1 RENAME COLUMN COL1 TO COL11; 

-- 컬럼 타입변경
ALTER TABLE EX1 MODIFY COL2 VARCHAR(30);

-- 컬럼 추가
ALTER TABLE EX1 ADD COL3 NUMBER;

-- 이미 생성된 테이블에 제약조건 추가하기
-- ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 제약조건종류(컬럼명);
-- EX1 테이블에 PK_EX1 이라는 이름으로 COL11에 PRIMARY KEY 부여
ALTER TABLE EX1 ADD CONSTRAINT PK_EX1 PRIMARY KEY(COL11);

-- 제약조건 삭제하기
-- ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
ALTER TABLE EX1 DROP CONSTRAINT PK_EX1;

DROP TABLE EX1;

-- TBL_ANIMAL 테이블 생성하기
-- 컬럼
-- ID 숫자 기본키로 만들기
-- "TYPE"(종) 문자 10글자까지
-- AGE 숫자
-- FEED 문자 10글자까지

CREATE TABLE TBL_ANIMAL(
	ID NUMBER PRIMARY KEY,
	"TYPE" VARCHAR2(10),
	AGE NUMBER,
	FEED VARCHAR2(10)
); 

-- 학생테이블
-- DEFAULT, CHECK 제약조건을 사용
CREATE TABLE TBL_STUDENT(
	ID NUMBER,
	NAME VARCHAR2(100),
	MAJOR VARCHAR2(100),
	GENDER CHAR(1) DEFAULT 'W' NOT NULL CONSTRAINT BAN_CHAR CHECK(GENDER='M' OR GENDER='W'),
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >= TO_DATE('1980-01-01','YYYY-MM-DD')),
	CONSTRAINT STD_PK PRIMARY KEY(ID)
);


DROP TABLE TBL_STUDENT;

CREATE TABLE TBL_STUDENT(
	ID NUMBER,
	NAME VARCHAR2(100),
	MAJOR VARCHAR2(100),
	GENDER CHAR(1) DEFAULT 'W' NOT NULL CONSTRAINT BAN_CHAR CHECK(GENDER='M' OR GENDER='W'),
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >= TO_DATE('1980-01-01','YYYY-MM-DD')),
	CONSTRAINT PK_STD PRIMARY KEY(ID)
);

--<< 칼럼 정보 >>
--
--1) NO : 제품번호, 숫자, 기본키
--
--2) NAME : 제품명, 문자열 최대 100바이트, 필수
--
--3) PRICE : 제품가격, 숫자
--
--4) P_DATE : 생산일자, 날짜

CREATE TABLE PRODUCT(
	"NO" NUMBER PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PRICE NUMBER,
	P_DATE DATE
);



